"""Catalogo didattico bilingue condiviso dalla UI LabPro.

Le schede non promettono conformita: separano sempre il modello simulato,
la misura osservabile e cio che richiederebbe una procedura normativa.
"""

from __future__ import annotations


def _topic(title_it, title_en, block, idea_it, idea_en, formula,
           observe_it, observe_en, experiment_it, experiment_en, limits_it,
           limits_en, course):
    return {
        "id": block,
        "title": {"it": title_it, "en": title_en},
        "idea": {"it": idea_it, "en": idea_en},
        "formula": formula,
        "observe": {"it": observe_it, "en": observe_en},
        "experiment": {"it": experiment_it, "en": experiment_en},
        "limits": {"it": limits_it, "en": limits_en},
        "course": course,
    }


TOPICS = [
    _topic("PPG, PRBS e mapper", "PPG, PRBS and mapper", "stimulus",
           "Il PPG crea la sequenza di bit; il mapper trasforma 1 bit/UI (NRZ) o 2 bit/UI (PAM4) in livelli elettrici.",
           "The PPG creates the bit sequence; the mapper turns 1 bit/UI (NRZ) or 2 bits/UI (PAM4) into electrical levels.",
           "R_b = R_s log2(M)",
           "Occupazione livelli, matrice delle transizioni e spettro dello stimolo.",
           "Level occupancy, transition matrix, and stimulus spectrum.",
           "Confronta PRBS13, clock 0101 e SSPR-like; osserva quanto cambia lo stress sul canale.",
           "Compare PRBS13, 0101 clock, and SSPR-like patterns; observe how channel stress changes.",
           "I pattern implementati sono didattici; non tutti hanno il bit ordering normativo di una clause.",
           "Implemented patterns are educational; not all use clause-defined bit ordering.", "ECEN 720"),
    _topic("FEC e reference plane", "FEC and reference plane", "fec",
           "Il decoder RS corregge errori di simbolo, non genericamente bit. Il punto di iniezione decide se il FEC puo vederli.",
           "The RS decoder corrects symbol errors, not generic bits. The injection plane determines whether FEC can see them.",
           "RS(n,k), t=(n-k)/2;  FER_iid=P[X>t]",
           "Errori/simbolo per codeword, frame corretti/persi/miscorretti e BER post-FEC.",
           "Symbol errors per codeword, corrected/lost/miscorrected frames, and post-FEC BER.",
           "Inserisci 1..20 errori e confronta errori raggruppati e dispersi.",
           "Inject 1..20 errors and compare clustered versus dispersed errors.",
           "Non sono presenti PCS, AM, scrambler e interleaving di clause.",
           "Clause PCS, AM, scrambler, and interleaving are not present.", "ECEN 720"),
    _topic("Serializer e clock TX", "Serializer and TX clock", "serpll",
           "Il serializer converte le lane parallele nel flusso seriale; il PLL ne imposta la base tempi e quindi il jitter trasmesso.",
           "The serializer converts parallel lanes into a serial stream; its PLL sets the time base and therefore transmitted jitter.",
           "TIE_TX = RJ + PJ sin(2 pi f_j t) + DCD",
           "TIE al driver, spettro del PJ, DCD e differenziale P/N.",
           "Driver TIE, PJ spectrum, DCD, and the P/N differential pair.",
           "Inietta prima PJ, poi RJ: il picco spettrale e il floor dell'istogramma rispondono in modo diverso.",
           "Inject PJ first, then RJ: the spectral line and histogram floor respond differently.",
           "Il modello e edge-jitter per UI, non una PSD completa di phase noise del PLL.",
           "The model is per-UI edge jitter, not a complete PLL phase-noise PSD.", "ECEN 720"),
    _topic("TX FFE, DAC e driver", "TX FFE, DAC and driver", "tx",
           "FFE anticipa/segue le transizioni per pre-compensare l'ISI; DAC e driver introducono quantizzazione, banda e clipping.",
           "FFE weights precursor/postcursor transitions to pre-compensate ISI; DAC and driver add quantization, bandwidth, and clipping.",
           "y[k]=sum c_i x[k-i];  H_DAC(f)=ZOH(f) H_BW(f)",
           "Swing cost, LSB, clipping, risposta FFE e eye al driver.",
           "Swing cost, LSB, clipping, FFE response, and driver eye.",
           "Aumenta il post-cursor finche l'eye migliora ma il driver inizia a clipppare.",
           "Increase post-cursor weight until the eye improves but the driver starts clipping.",
           "Nessun modello transistor-level, package non lineare o supply noise.",
           "No transistor-level, nonlinear-package, or supply-noise model.", "ECEN 720"),
    _topic("Canale, S-parameter e crosstalk", "Channel, S-parameters and crosstalk", "channel",
           "Loss, return loss, eco e group delay trasformano impulsi isolati in ISI; S4P permette di separare modo differenziale e conversione di modo.",
           "Loss, return loss, echoes, and group delay turn isolated pulses into ISI; S4P separates differential transmission and mode conversion.",
           "SDD21=(S21-S23-S41+S43)/2",
           "IL/RL, impulse cursor, SDD21/SCD21, NEXT/FEXT e eye dopo il canale.",
           "IL/RL, impulse cursors, SDD21/SCD21, NEXT/FEXT, and post-channel eye.",
           "Carica un S4P, cambia il port mapping e verifica che SCD21 non venga scambiato per perdita differenziale.",
           "Load an S4P, change port mapping, and verify that SCD21 is not mistaken for differential loss.",
           "Il tool usa SDD21 nel main path ma non e un calcolo COM normativo.",
           "The tool uses SDD21 in the main path but is not a normative COM calculation.", "ECEN 720"),
    _topic("Laser, modulatori e propagazione IM/DD", "Lasers, modulators, and IM/DD propagation", "optical",
           "CW-DFB+MZM, DFB-EML, DFB-DML e VCSEL hanno transfer, ER e chirp diversi. In SMF il campo accumula beta2, beta3, PMD e Kerr; in MMF domina anche il bandwidth-distance modale.",
           "CW-DFB+MZM, DFB-EML, DFB-DML, and VCSEL have different transfer, ER, and chirp. In SMF the field accumulates beta2, beta3, PMD, and Kerr effects; MMF also has modal bandwidth-distance limitation.",
           "H_CD=exp[-jL(beta2*w^2/2+beta3*w^3/6)]; DGD=PMD*sqrt(L); phi_NL=gamma*L_eff*P",
           "Architettura sorgente/modulatore, OMA/ER, linewidth, beta2/beta3, DGD, fase Kerr, BW modale, budget e eye.",
           "Source/modulator architecture, OMA/ER, linewidth, beta2/beta3, DGD, Kerr phase, modal BW, budget, and eye.",
           "Confronta EML-SMF a 1310/1550 nm e VCSEL-MMF a 850 nm; poi azzera singolarmente slope, PMD, linewidth e Kerr.",
           "Compare EML-SMF at 1310/1550 nm with VCSEL-MMF at 850 nm; then zero slope, PMD, linewidth, and Kerr one by one.",
           "Il modello e system-level IM/DD: PMD e DML/VCSEL sono proxy large-signal; non include DMD risolto per modi, rate equations, reflections distribuite o una catena coherent-IQ.",
           "This is a system-level IM/DD model: PMD and DML/VCSEL are large-signal proxies; it does not include mode-resolved DMD, laser rate equations, distributed reflections, or a coherent-IQ chain.", "ECEN 721"),
    _topic("PD, TIA e noise budget", "PD, TIA and noise budget", "rxfe",
           "Il PD genera shot/RIN; il TIA aggiunge rumore d'ingresso, banda, guadagno e saturazione.",
           "The PD adds shot/RIN noise; the TIA adds input noise, bandwidth, gain, and saturation.",
           "S_i,shot=2q(I_sig+I_dark);  S_i,RIN=RIN I_sig^2",
           "PSD/ENBW, contributi RMS, clip del PD/TIA e SNR allo slicer.",
           "PSD/ENBW, RMS contributors, PD/TIA clipping, and slicer SNR.",
           "Riduci la potenza laser: identifica il passaggio da RIN-limited a TIA/shot-limited.",
           "Reduce laser power and identify the transition from RIN-limited to TIA/shot-limited.",
           "Le sorgenti sono gaussiane/stazionarie; non include APD excess noise o burst reali.",
           "Sources are Gaussian/stationary; APD excess noise and real bursts are not included.", "ECEN 721"),
    _topic("CTLE", "CTLE", "ctle",
           "Zero e poli compensano la pendenza del canale ma amplificano anche rumore e crosstalk.",
           "Zeros and poles compensate channel roll-off while also enhancing noise and crosstalk.",
           "H(s)=G0 (1+s/wz)/[(1+s/wp1)(1+s/wp2)]",
           "Peaking, group delay, eye e BER end-to-end.",
           "Peaking, group delay, eye, and end-to-end BER.",
           "Muovi separatamente zero, primo polo e polo alto; non cercare solo una risposta piatta.",
           "Move the zero, first pole, and high-frequency pole separately; do not optimize flatness alone.",
           "E un filtro lineare continuo ideale, non una rete analogica con PVT.",
           "It is an ideal continuous-time linear filter, not an analog network with PVT.", "ECEN 720"),
    _topic("ADC interleaved", "Interleaved ADC", "adc",
           "Quantizzazione, aperture jitter e mismatch fra interleave creano errori con firme spettrali diverse.",
           "Quantization, aperture jitter, and interleave mismatch create errors with different spectral signatures.",
           "SNR_q approx 6.02N+1.76 dB;  e_j approx 2 pi f_in sigma_t",
           "Clip, LSB, SNDR proxy, spur di interleave e sensibilita alla fase.",
           "Clipping, LSB, SNDR proxy, interleave spurs, and phase sensitivity.",
           "Esegui il tone lab cambiando separatamente gain, offset e skew mismatch.",
           "Run the tone lab while changing gain, offset, and skew mismatch separately.",
           "Non modella metastabilita, INL/DNL statiche complete o clock distribution fisica.",
           "It does not model metastability, full static INL/DNL, or physical clock distribution.", "ECEN 720"),
    _topic("CDR e timing loop", "CDR and timing loop", "timing",
           "TED, loop PI e NCO chiudono l'anello che decide davvero gli istanti usati dal datapath.",
           "TED, PI loop, and NCO close the loop that actually selects datapath sampling instants.",
           "e_G=(y_late-y_early)y_mid;  f_NCO[k+1]=f_NCO[k]+K_i e[k]",
           "Lock, fase, ppm stimati, cycle slip, pattern correlation e JTOL-lite.",
           "Lock, phase, estimated ppm, cycle slips, pattern correlation, and JTOL-lite.",
           "Applica offset ppm e PJ vicino alla banda del loop; osserva tracking e jitter peaking.",
           "Apply ppm offset and PJ near loop bandwidth; observe tracking and jitter peaking.",
           "Il pattern lock e BERT-style; non implementa AN/LT o un CDR transistor-level.",
           "Pattern lock is BERT-style; AN/LT and transistor-level CDR are not implemented.", "ECEN 720"),
    _topic("FSE, DFE e slicer", "FSE, DFE and slicer", "eq",
           "L'FSE rimuove ISI lineare con campioni frazionari; il DFE cancella post-cursor usando decisioni passate e puo propagare errori.",
           "The FSE removes linear ISI using fractional samples; the DFE cancels postcursor ISI using past decisions and can propagate errors.",
           "y[k]=w^T x[k]-sum b_i d[k-i]",
           "Tap trajectory, learning error, confusion matrix, Q, GMI e burstiness.",
           "Tap trajectory, learning error, confusion matrix, Q, GMI, and burstiness.",
           "Confronta supervised training e decision-directed region su un link vicino alla soglia.",
           "Compare supervised training and the decision-directed region on a near-threshold link.",
           "Training symbols are known; coefficient quantization and hardware saturation are absent.",
           "Training symbols are known; coefficient quantization and hardware saturation are absent.", "ECEN 720"),
    _topic("DCA: eye, mask e jitter", "DCA: eye, mask, and jitter", "scope",
           "Un DCA ricostruisce una distribuzione di ampiezza e tempo; eye, istogrammi e TIE sono viste diverse degli stessi crossing.",
           "A DCA reconstructs an amplitude/time distribution; eyes, histograms, and TIE are different views of the same crossings.",
           "TIE=t_cross-t_ideal;  Q=(mu_hi-mu_lo)/(sigma_hi+sigma_lo)",
           "Persistenza, eye height/width, mask hit, rise/fall, TIE, spettro e bathtub empirica.",
           "Persistence, eye height/width, mask hits, rise/fall, TIE, spectrum, and empirical bathtub.",
           "Aggancia due scope a nodi diversi e modifica un solo blocco: verifica la localita dell'effetto.",
           "Attach two scopes to different nodes and change one block: verify effect locality.",
           "Mask e bathtub sono proxy didattici, non procedure FlexDCA/IEEE calibrate.",
           "Mask and bathtub are educational proxies, not calibrated FlexDCA/IEEE procedures.", "ECEN 720 / 721"),
    _topic("BERT PPG/ED", "BERT PPG/ED", "bert",
           "Il PPG genera pattern/stress; l'ED richiede pattern lock e confronta bit, simboli e posizione degli errori.",
           "The PPG generates patterns/stress; the ED requires pattern lock and compares bits, symbols, and error location.",
           "BER=N_bit_err/N_bit;  SER=N_sym_err/N_sym",
           "Lock/loss, BER/SER, MSB/LSB, error map, error insertion e JTOL.",
           "Lock/loss, BER/SER, MSB/LSB, error map, error insertion, and JTOL.",
           "Inietta RJ, PJ e bit error separatamente; identifica quale misura discrimina lo stress.",
           "Inject RJ, PJ, and bit errors separately; identify which measurement discriminates each stress.",
           "Workflow ispirato a un BERT; non e software o procedura MP1900A.",
           "BERT-inspired workflow; it is not MP1900A software or procedure.", "ECEN 720"),
    _topic("Traffic generator/analyzer", "Traffic generator/analyzer", "l2",
           "Frame, FCS e sequence number permettono di distinguere bit error, frame corrotti e frame persi.",
           "Frames, FCS, and sequence numbers distinguish bit errors, corrupted frames, and lost frames.",
           "Throughput=payload_FCS_OK/time;  FLR=N_lost/N_expected",
           "Frame detected/OK/FCS-bad/lost, throughput e sweep della frame size.",
           "Detected/OK/FCS-bad/lost frames, throughput, and frame-size sweep.",
           "Esegui il benchmark 64..1024 B e osserva overhead e sensibilita agli errori.",
           "Run the 64..1024-byte benchmark and observe overhead and error sensitivity.",
           "Non e Xena/RFC 2544: niente DUT di rete, latency, multi-stream, QoS o rate control.",
           "This is not Xena/RFC 2544: no network DUT, latency, multi-stream, QoS, or rate control.", "ECEN 720"),
    _topic("Profili IEEE/OIF", "IEEE/OIF profiles", "standards",
           "Uno standard specifica reference plane, pattern, maschere e procedure; un preset del simulatore imposta solo un contesto fisico riproducibile.",
           "A standard defines reference planes, patterns, masks, and procedures; a simulator preset only creates a reproducible physical context.",
           "PASS simulatore != conformita; serve la procedura della clause/IA",
           "Stato pubblicato/draft, mezzo, reach, rate/lane, FEC modellato e limite del claim.",
           "Published/draft status, medium, reach, rate/lane, modeled FEC, and claim boundary.",
           "Carica due profili con la stessa lane rate ma reach diversi e confronta quali blocchi cambiano.",
           "Load two profiles with the same lane rate but different reach and compare which blocks change.",
           "Nessun risultato del banco va chiamato compliance senza fixture, calibration e test normative.",
           "No bench result should be called compliance without normative fixtures, calibration, and tests.", "ECEN 720 / 721"),
]


TOPICS_BY_ID = {t["id"]: t for t in TOPICS}
