"""Export dei report in formato strumento (Markdown, XML/CSV) dalle
procedure di ``serdes_sim.instrument_procedures``.

I nomi di sezione e di colonna seguono i report reali (Valkyrie2544 PDF/XML,
SAMComplete Y.1564, riquadro Result PAM4 dell'MP1900A) perché l'utente possa
confrontare un export LabPro con un report di strumento riga per riga.
"""

from __future__ import annotations

from xml.sax.saxutils import escape

THROUGHPUT_KEYS = ("Frame Size", "Result State", "Tx Off.Rate (Percent)", "Tx (Frames)",
                   "Tx Rate (L1) (Bit/s)", "Tx Rate (L2) (Bit/s)", "Tx Rate (Fps)", "Rx (Frames)",
                   "Loss (Frames)", "Loss Rate (Percent)", "BER (est)")
LATENCY_KEYS = ("Frame Size", "Result State", "Tx Off.Rate (Percent)", "Tx (Frames)", "Rx (Frames)",
                "Avg Latency (micsec)", "Min Latency (micsec)", "Max Latency (micsec)",
                "Avg Jitter (micsec)", "Min Jitter (micsec)", "Max Jitter (micsec)")
LOSS_KEYS = ("Frame Size", "Rate (Percent)", "Result State", "Tx (Frames)", "Tx Rate (Fps)",
             "Tx Rate (L1) (Bit/s)", "Rx (Frames)", "Rx Rate (Fps)", "Rx Rate (L1) (Bit/s)",
             "Loss (Frames)", "Loss Rate (Percent)")
B2B_KEYS = ("Frame Size", "Result State", "Tx Burst (Frames)", "Tx Burst (Bytes)",
            "Max Offered Rate (Fps)", "Max Offered Rate (Bit/s)")
Y1564_CFG_KEYS = ("Service", "Step", "Frame Size", "CIR (Mbps)", "EIR (Mbps)", "Offered (Mbps)",
                  "IR (Mbps)", "FTD (µs)", "FDV (µs)", "FLR (%)", "Tx (Frames)", "Rx (Frames)", "Result")
Y1564_PERF_KEYS = ("Service", "Frame Size", "CIR (Mbps)", "IR (Mbps)", "FTD (µs)", "FDV (µs)",
                   "FLR (%)", "Availability (%)", "Tx (Frames)", "Rx (Frames)", "Result")


def _fmt(v):
    if v is None:
        return "—"
    if isinstance(v, float):
        if v == 0:
            return "0"
        if abs(v) >= 1e9:
            return f"{v / 1e9:,.2f} G"
        if abs(v) >= 1e6 and abs(v) < 1e9 and v == int(v):
            return f"{int(v):,}"
        if abs(v) < 1e-3:
            return f"{v:.3e}"
        return f"{v:,.3f}"
    return str(v)


def _table(rows, keys):
    if not rows:
        return "_no rows_\n"
    head = "| " + " | ".join(keys) + " |\n|" + "|".join(" --- " for _ in keys) + "|\n"
    body = "".join("| " + " | ".join(_fmt(r.get(k)) for k in keys) + " |\n" for r in rows)
    return head + body


def _kv(d):
    return "".join(f"- **{k}:** {_fmt(v)}\n" for k, v in d.items())


def rfc2544_markdown(rep: dict) -> str:
    out = ["# Valkyrie2544-style Test Report (LabPro)\n", "## Test Summary\n", _kv(rep["test_summary"]),
           "\n## Test Setup\n### Main Test Options\n", _kv(rep["test_setup"]),
           "\n### Port Configuration\n", _kv(rep["port_configuration"]),
           "\n## Throughput Test Results\n### Test Setup\n", _kv(rep["throughput_setup"]),
           f"\n### Test Results\n{rep['summary']['message']}\n\n", _table(rep["throughput"], THROUGHPUT_KEYS),
           "\n## Latency and Jitter Test Results\n", _table(rep["latency_jitter"], LATENCY_KEYS),
           "\n## Frame Loss Rate Test Results\n", _table(rep["frame_loss"], LOSS_KEYS),
           "\n## Back-to-Back Test Results\n", _table(rep["back_to_back"], B2B_KEYS),
           f"\n## Declared boundary\n{rep['declared']}\n",
           f"\nVerdict: **{rep['verdict']['model']}** (model criterion, IEEE/RFC compliance NOT ASSESSED)\n"]
    return "".join(out)


def rfc2544_xml(rep: dict) -> str:
    """XML nello spirito della 'XML Report Specification for Xena Test
    Applications' (elementi TestDateTime, TestDuration, FrameSize, ...)."""
    def el(tag, val, indent=2):
        return f"{' ' * indent}<{tag}>{escape(str(val))}</{tag}>\n"

    def rows(tag, rows_, keys):
        s = f" <{tag}>\n"
        for r in rows_:
            s += "  <Result>\n"
            for k in keys:
                s += el(k.replace(" ", "").replace("(", "_").replace(")", "").replace("/", "").replace(".", ""), _fmt(r.get(k)), 3)
            s += "  </Result>\n"
        return s + f" </{tag}>\n"

    s = '<?xml version="1.0" encoding="utf-8"?>\n<Xena2544Report Generator="LabPro" Style="Valkyrie2544">\n'
    s += " <TestSummary>\n"
    s += el("TestDateTime", rep["test_summary"]["Test Date and Time"])
    s += el("TestDuration", rep["test_summary"]["Test Duration (h:m:s)"])
    s += el("GeneratedBy", rep["test_summary"]["Generated By"])
    s += el("Verdict", rep["verdict"]["model"])
    s += " </TestSummary>\n <TestSetup>\n"
    for k, v in rep["test_setup"].items():
        s += el(k.replace(" ", "").replace("-", ""), v)
    for k, v in rep["port_configuration"].items():
        s += el(k.replace(" ", ""), v)
    s += " </TestSetup>\n"
    s += rows("ThroughputTest", rep["throughput"], THROUGHPUT_KEYS)
    s += rows("LatencyJitterTest", rep["latency_jitter"], LATENCY_KEYS)
    s += rows("FrameLossTest", rep["frame_loss"], LOSS_KEYS)
    s += rows("BackToBackTest", rep["back_to_back"], B2B_KEYS)
    s += el("Declared", rep["declared"], 1)
    return s + "</Xena2544Report>\n"


def y1564_markdown(rep: dict) -> str:
    out = ["# SAMComplete-style Y.1564 Report (LabPro)\n", "## Test Summary\n", _kv(rep["test_summary"]),
           "\n## SLA\n", _kv(rep["sla"]),
           "\n## Services\n", _table(rep["services"], ("name", "frame_bytes", "cir_mbps", "eir_mbps")),
           "\n## Service Configuration Test\n", _table(rep["service_configuration"], Y1564_CFG_KEYS),
           "\n## Service Performance Test\n", _table(rep["service_performance"], Y1564_PERF_KEYS),
           f"\n{rep['summary']['message']}\n\n## Declared boundary\n{rep['declared']}\n",
           f"\nVerdict: **{rep['verdict']['model']}** (model criterion)\n"]
    return "".join(out)


def y1564_csv(rep: dict) -> str:
    lines = ["Phase," + ",".join(Y1564_CFG_KEYS)]
    for r in rep["service_configuration"]:
        lines.append("Service Configuration," + ",".join(_fmt(r.get(k)).replace(",", "") for k in Y1564_CFG_KEYS))
    lines.append("Phase," + ",".join(Y1564_PERF_KEYS))
    for r in rep["service_performance"]:
        lines.append("Service Performance," + ",".join(_fmt(r.get(k)).replace(",", "") for k in Y1564_PERF_KEYS))
    return "\n".join(lines) + "\n"


def bert_markdown(res: dict) -> str:
    if not res.get("available"):
        return f"# Result PAM4 (MP1900A-style)\n\n_{res.get('reason')}_\n"
    lanes = res["lanes"]
    m = res["symbol_error_matrix"]
    out = ["# Result PAM4 (MP1900A-style, LabPro)\n\n| | Total | INS | OMI |\n| --- | --- | --- | --- |\n"]
    for lane in ("MSB", "LSB"):
        v = lanes[lane]
        out.append(f"| {lane} ER | {v['ER']:.3e} | {v['INS']['ER']:.3e} | {v['OMI']['ER']:.3e} |\n")
        out.append(f"| {lane} EC | {v['EC']} | {v['INS']['EC']} | {v['OMI']['EC']} |\n")
    out.append("\n## PAM4 symbol error cases (tx level → rx level)\n\n| tx \\ rx | Level 0 | Level 1 | Level 2 | Level 3 |\n| --- | --- | --- | --- | --- |\n")
    for i, row in enumerate(m["counts"]):
        out.append(f"| Level {i} | " + " | ".join(str(v) for v in row) + " |\n")
    out.append(f"\nSymbol errors: {m['total_symbol_errors']} / {res['symbols_measured']} (SER {m['symbol_error_ratio']:.3e})\n")
    out.append("\n## Cumulative\n" + _kv(res["cumulative"]) + f"\n{res['declared']}\n")
    return "".join(out)


def bert_csv(res: dict) -> str:
    if not res.get("available"):
        return "Result PAM4,unavailable\n"
    lanes = res["lanes"]
    lines = ["Lane,Item,Total,INS,OMI"]
    for lane in ("MSB", "LSB"):
        v = lanes[lane]
        lines.append(f"{lane},ER,{v['ER']:.6e},{v['INS']['ER']:.6e},{v['OMI']['ER']:.6e}")
        lines.append(f"{lane},EC,{v['EC']},{v['INS']['EC']},{v['OMI']['EC']}")
    lines.append("Symbol errors,tx level,to Level 0,to Level 1,to Level 2,to Level 3")
    for i, row in enumerate(res["symbol_error_matrix"]["counts"]):
        lines.append(f"EC,Level {i}," + ",".join(str(v) for v in row))
    for k, v in res["cumulative"].items():
        lines.append(f"Cumulative,{k},{'' if v is None else v}")
    return "\n".join(lines) + "\n"
